# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'projet_debut' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

    pod 'SwiftKeychainWrapper', '~> 3.0'

  # Pods for projet_debut

  target 'projet_debutTests' do

    inherit! :search_paths
    # Pods for testing
  end

  target 'projet_debutUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
